### ISSUE TITLE
[BUG] Incorrect usage of the X-Iceberg-Access-Delegation header

### ISSUE THREAD

**Issue by dimas-b** [apache/polaris#146]
### Is this a possible security vulnerability?

- [X] This is NOT a possible security vulnerability

### Describe the bug

[Iceberg REST spec defines](https://github.com/apache/iceberg/blob/apache-iceberg-1.6.0/open-api/rest-catalog-open-api.yaml#L1489) the following two values for the `X-Iceberg-Access-Delegation` HTTP header:
* `vended-credentials`
* `remote-signing`

However, current Polaris examples / docs use the value of `true`, which does not match anything in the Iceberg REST spec.

Current code appears to treat any non-empty header as `vended-credentials`, which is not exactly correct.

### Expected Behavior

* `vended-credentials` value is respected. 
* `remote-signing` is clearly reported as an error (for now, cf. #32).

**Comment by dennishuo** [comment]
This was definitely an unfortunate oversight; good catch!

Luckily, since the bug wasn't that the request handlers actually expected to parse `true` from the String, just that they only checked `!isNullOrEmpty` to assume it meant vended-credentials, it's forward-compatible if anyone is using the "correct" syntax.

We should try to update docs as quickly as possible to reduce the degree to which `X-Iceberg-Access-Delegation: true` gets entrenched into various workflows or test scripts of anyone integrating with Polaris.

At this point it may already be prudent to have an option for still falling back to the `vended-credentials` behavior if none of the comma-separated list of supported mechanisms is recognized (including the string "true").

**Comment by eric-maynard** [comment]
Hey @dimas-b , I think you fixed this in #211, right?

**Comment by eric-maynard** [comment]
This seems fixed so I'm closing it out for now -- please re-open if need be.

**Comment by dimas-b** [comment]
Yes, #211 fixes this... not sure how I forgot to cross-reference :facepalm:
