### ISSUE TITLE
[FEATURE REQUEST]Service Connection Per namespace in a catalog

### ISSUE THREAD

**Issue by chetan-habu** [apache/polaris#194]
### Is your feature request related to a problem? Please describe.

Restrict access to tables in a namespace to a service connection

### Describe the solution you'd like

I want to create one catalog and multiple child namespaces under a parent namespace. Each namespace will have their own service connection and individual service connection can only talk to catalog data in the namespace.

### Describe alternatives you've considered

I would have to create a catalog ,namespace and service connection inorder to provide limited access to a single service connection

**Comment by sfc-gh-ygu** [comment]
I'm not sure I understand completely, but you can create the `catalog roles` with specific privileges on a single namespace. The concept `catalog role` can be a group of privileges on namespace/table/view/catalog. Here is the RBAC example for reference, https://polaris.io/#tag/Access-Control/RBAC-example
 
![image](https://github.com/user-attachments/assets/45cda16c-8d6d-4ecd-b0b3-6181be4f408b)

**Comment by chetan-habu** [comment]
Thanks . Creating catalog roles per namespace should help take care of our usecases. Are there any limitations to the number of principal roles, catalog roles and catalog per polaris instance

**Comment by flyrain** [comment]
I don't think there will be limitations on these numbers. cc @dennishuo @collado-mike @eric-maynard  for more details.

**Comment by chetan-habu** [comment]
@flyrain I was able to use your suggestion and create catalog role per namespace and then map it later to a principal role and service principal. I am using Snowflake managed polaris to create all the desired configurations. Do you have any idea how I could get the service admin credentials. I want to use APIs to create catalog ,namespace and other polaris related configurations but the only way I am able to do that is get the token from the network tab and use that to invoke APIs.

**Comment by eric-maynard** [comment]
Hey @chetan-habu, if you have questions about a vendor-managed offering please reach out to that vendor. With Apache Polaris, you can view the root credentials during bootstrapping.

**Comment by collado-mike** [comment]
Snowflake's Polaris doesn't yet let you do this, but the functionality exists in the OSS project. Unsure when the feature will be released in the managed Polaris offering.

**Comment by chetan-habu** [comment]
Thanks team. Can you help provide some more insights to the following questions if any.

- limits to the number of catalogs we can create in a polaris instance
- Number of namespaces/sub namespaces a catalog can have
- catalog roles per namespace
- service principals.

We plan to create a catalog and then namespaces are our logical grouping . Each namespace would be associated with a catalog role which allows access to the namespace tables only. the catalog role will have an associated service principal. We would leverage the apis from the documentation to create the whole piece and hence the ask on the limits .

**Comment by eric-maynard** [comment]
Hey @chetan-habu, following up on the above:

* limits to the number of catalogs we can create in a polaris instance
  - Currently, there is no limit. You might hit practical limits on the metastore side depending on your implementation

* Number of namespaces/sub namespaces a catalog can have
  - Same as the above

* catalog roles per namespace
  - Same as the above

* service principals.
  - Currently, Polaris doesn't really have a concept of a service principal, but you can create as many principals as you wish.

As you can see, Polaris itself doesn't have hard limits on the number of entities you can create right now. But since everything is stored in the metastore, there could be practical limits on some entities. In particular, some checks we do to ensure path uniqueness or that catalog paths don't overlap are linear or worse time in the eclipse-link metastore.

**Comment by chetan-habu** [comment]
Thank you , this helps. Closing the issue
